version: '3.9'
services:
  db:
    image: postgres:15
    container_name: argandici-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: argandici
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: argandici-api
    restart: unless-stopped
    env_file:
      - ./api/.env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/argandici
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: argandici
    ports:
      - "3000:3000"
    depends_on:
      - db

  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    container_name: argandici-ui
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      API_URL: http://api:3000
    depends_on:
      - api

volumes:
  db-data:
