version: '3.9'
services:
  db:
    image: postgres:15
    container_name: argandici-db
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: development
    container_name: argandici-api
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./api:/usr/src/app
      - api_node_modules:/usr/src/app/node_modules

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
      target: dev
    container_name: argandici-ui
    restart: unless-stopped
    environment:
      API_URL: http://api:3000
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "4000:4000"
    depends_on:
      - api
    volumes:
      - ./ui:/app
      - ui_node_modules:/app/node_modules

volumes:
  db-data:
  api_node_modules:
  ui_node_modules:
